version: '3.8'
services:
  server:
    build: 
      context: ./dockerfiles
      dockerfile: server.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: vietdz1304
      MONGO_INITDB_ROOT_PASSWORD: vietdz1304

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8090:8090
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vietdz1304
      ME_CONFIG_MONGODB_ADMINPASSWORD: vietdz1304
      ME_CONFIG_MONGODB_URL: mongodb://vietdz1304:vietdz1304@mongo:27017/

  client:
    build:
      context: ./dockerfiles
      dockerfile: client.dockerfile
    ports:
      - "3001:3000"